import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Clerk App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Add any Clerk stuff here, currently the following are public pages.
            <ul>
              <li><a href="/sign-in">Sign In</a></li>
              <li><a href="/sign-up">Sign Up</a></li>
              <li><a href="/">This page</a></li>
            </ul>
          </p>           
        </div>
      </main>
    </>
  )
}
